### ISSUE TITLE
Add these to [image board]

### ISSUE THREAD

**Issue by zcyzcy88** [soruly/awesome-acg#19]
gelbooru
danbooru
sankaku complex

No PR because I am lazy -_-

**Comment by soruly** [comment]
I'll have to see if these websites have open-sourced or has something like APIs that helps developers build software. Because personally, I'd like to keep this a list of stuffs that developers would be interested to know, to learn from, or to give inspirations, rather than simply a list of well-known anime websites.

**Comment by zcyzcy88** [comment]
Yes, danbooru has open its sorce code: https://github.com/r888888888/danbooru
And some others are based on it.

**Comment by soruly** [comment]
Added danbooru
